name: "Validate and Deploy Databricks Bundle"
description: "Validate and deploy a Databricks Asset Bundle to the target environment"

inputs:
  target:
    description: "Deployment target (dev/uat/prod)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Databricks CLI and Dependencies
      shell: bash
      run: |
        echo "Installing Databricks CLI..."
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        databricks --version
        
        echo "Installing uv package manager..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.cargo/bin:$PATH"
        uv --version || echo "⚠️ uv installation may require shell restart"
        
    - name: Load Environment Config
      shell: bash
      run: |
        REPO_PATH=${WORKING_REPO_PATH:-"."}
        ENV_FILE="$REPO_PATH/env/${{ inputs.target }}.txt"
        
        echo "Loading environment variables for ${{ inputs.target }}..."
        
        if [ ! -f "$ENV_FILE" ]; then
          echo "❌ Environment file not found: $ENV_FILE"
          echo "Available files in $REPO_PATH/env/:"
          ls -la "$REPO_PATH/env/" 2>/dev/null || echo "env directory not found"
          exit 1
        fi
        
        while IFS='=' read -r key value || [ -n "$key" ]; do
          [[ $key =~ ^[[:space:]]*# ]] && continue
          [[ -z "$key" ]] && continue
          
          key=$(echo "$key" | xargs)
          value=$(echo "$value" | xargs)
          echo "${key}=${value}" >> $GITHUB_ENV
        done < "$ENV_FILE"
        
        echo "✅ Environment variables loaded successfully"
        
    - name: Validate Databricks Bundle
      shell: bash
      run: |
        REPO_PATH=${WORKING_REPO_PATH:-"."}
        cd "$REPO_PATH"
        
        echo "Validating Databricks Bundle for ${{ inputs.target }}..."
        
        if databricks bundle validate --target "${{ inputs.target }}"; then
          echo "✅ Bundle validation successful"
        else
          echo "❌ Bundle validation failed"
          exit 1
        fi
        
    - name: Deploy Databricks Bundle
      shell: bash
      run: |
        REPO_PATH=${WORKING_REPO_PATH:-"."}
        cd "$REPO_PATH"
        
        # Ensure uv is in PATH for the deployment
        export PATH="$HOME/.cargo/bin:$PATH"
        
        echo "Deploying Databricks Bundle to ${{ inputs.target }}..."
        
        if databricks bundle deploy --target "${{ inputs.target }}"; then
          echo "✅ Bundle deployed successfully"
        else
          echo "❌ Bundle deployment failed"
          exit 1
        fi
