name: "Databricks CI/CD"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (dev/uat/prod)"
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Working Repo
        uses: actions/checkout@v4
        with:
          path: working-repo
          
      - name: Checkout Template Repo
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/ADB-Template
          path: template-repo
          ref: main
          
      - name: Azure OIDC Login
        uses: ./template-repo/actions/login
        with:
          environment: ${{ inputs.environment }}
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}
          
      - name: Validate and Deploy Bundle
        uses: ./template-repo/actions/deploy
        with:
          target: ${{ inputs.environment }}
        env:
          WORKING_REPO_PATH: ./working-repo
